#logging:
#  level:
#    root: INFO
#    org.springframework.web: INFO
#    org.springframework.security: INFO
#
#spring:
#  jpa:
#    hibernate:
#      use-new-id-generator-mappings: false
#
#aws:
#  dynamodb:
#    endpoint: https://dynamodb.us-east-1.amazonaws.com
